### ISSUE TITLE
github action error

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidyseurat#15]
Hello @mblue9 when you have time, no rush. Could you please give me a hand with a github action error. :) in the master branch

```
Invoke-History: D:\a\_temp\2992a0a4-6162-4b5d-8d0d-febac0ff55cb.ps1:2
Line |
   2 |  R CMD INSTALL .
     |  ~~~~~~~~~~~~~~~
     | A positional parameter cannot be found that accepts argument 'INSTALL'.

Error: Process completed with exit code 1.
```

**Comment by mblue9** [comment]
Sorry I seem to have missed these github notifications from last week, I'll have a look at this

**Comment by mblue9** [comment]
I think this should fix it https://github.com/stemangiola/tidyseurat/pull/16

**Comment by mblue9** [comment]
Closing as fixed.
