### ISSUE TITLE
Bug in get_abundance_sc_long

### ISSUE THREAD

**Issue by genec1** [stemangiola/tidyseurat#17]
In trying and failing to get `join_transcripts` to work on a CITE marker (it was returning an empty tibble), I found that the problem was in `get_abundance_sc_long`.  I found that the `Reduce` call was returning empty results when there were multiple assays, and only one assay had results.  The fix was running Reduce only on non-empty results:

original:
```
        values_drop_na = TRUE)) %>% Reduce(function(...) left_join(..., 
        by = c("transcript", "cell")), .)
```

fix:
```
        values_drop_na = TRUE)) -> assay_results   # save intermediate results
	has_data <- assay_results %>% map(nrow) %>% unlist %>%  `>`(0). # check which tibbles are note empty
	Reduce(function(...) left_join(..., by=c("transcript", "cell")), assay_results[has_data]) # only Reduce non-empty tibbles

```

**Comment by stemangiola** [comment]
Thanks @genec1 for the very useful issue, with solution

Would you be able to send through (google drive or others) a minimal (anonymized if you wish) data set that reproduces this bug?

In this way I will be able to implement your solution.

If you feel opening a pull request (with unit test) would be amazing. But I am aware that not everyone is keen. An example dataset would suffice.

**Comment by genec1** [comment]
Here is a tiny data set for testing, which I will leave up for the duration fo the day:
https://www.dropbox.com/s/hzwalm4fen7og83/test_scrna_for_tidyseurat.rdata?dl=0

I thought of a better fix for the problem.  Rather than a left_join, it should be a full_join.

**Comment by stemangiola** [comment]
Hello @genec1 ,

with your test dataset I get 

```r
test_scrna %>%
 tidy() %>% 
 join_transcripts(c("Rpl14",  "Myl12a" ,"Gpi1",   "H3f3a" , "Cox6b1"))
```
```
tidyseurat says: A data frame is returned for independent data analysis.
# A tibble: 90 x 12
   cell  transcript abundance_RNA abundance_CITE orig.ident nCount_RNA nFeature_RNA nCount_CITE nFeature_CITE
   <chr> <chr>              <dbl>          <dbl> <chr>           <dbl>        <int>       <dbl>         <int>
 1 CT_C… Rpl14              3.18              NA CT                 39            5           5             4
 2 CT_C… Myl12a             1.61              NA CT                 39            5           5             4
 3 CT_C… Gpi1               1.61              NA CT                 39            5           5             4
 4 CT_C… H3f3a              2.08              NA CT                 39            5           5             4
 5 CT_C… Cox6b1             0.693             NA CT                 39            5           5             4
 6 CT_G… Rpl14              3.36              NA CT                 46            5          21             7
 7 CT_G… Myl12a             1.38              NA CT                 46            5          21             7
 8 CT_G… Gpi1               1.38              NA CT                 46            5          21             7
 9 CT_G… H3f3a              2.08              NA CT                 46            5          21             7
10 CT_G… Cox6b1             1.79              NA CT                 46            5          21             7
# … with 80 more rows, and 3 more variables: percent.mt <dbl>, percent.ribo <dbl>, REMOVE <lgl>
```

I don't see this as "an empty tibble". It is returning an empty column because one assay is empty. Which is what I think should indeed return. This is telling you that something is funny in the datasets.

If we omit columns on non so transparent criteria, the user can have the doubt of what is going on, while the answer can be simply, something that should have fillet that column did not.

Am I getting this right?

**Comment by genec1** [comment]
The error occurs when requesting a feature from the second assay ("CITE").  Try something like:

```
test_scrna %>%
 tidy() %>% 
 join_transcripts(c("CD14-mouse", "CD11C-mouse"))
```

**Comment by stemangiola** [comment]
I see. So for a consistent behavior I believe we should use full_join, so the user will see there are many assays but they don't share the same features.

**Comment by genec1** [comment]
Agreed, full_join is my recommended fix.

**Comment by stemangiola** [comment]
Sure, you mentioned it before. 

Cool, I will implement that!

**Comment by stemangiola** [comment]
Integrated. Thanks for your issue!
