### ISSUE TITLE
DESCRIPTION: URL and BugReports field

### ISSUE THREAD

**Issue by HenrikBengtsson** [stemangiola/tidyseurat#32]
Nice package.  Please consider adding fields `URL` and `BugReports` to make it easy to find this repo from https://cran.r-project.org/package=tidyseurat

**Comment by stemangiola** [comment]
Thanks, done here https://github.com/stemangiola/tidyseurat/commit/5e02baa9240fdf74337fc6d10e9ac3892d9ef8f2

Out of curiosity, @HenrikBengtsson do you do single-cell analyses or you are targeting a bunch of projects?

**Comment by HenrikBengtsson** [comment]
Hi. Yes, I've done/do some work on some single-cell analysis.  For instance, a few years ago I ran some Seurat analysis for a collaborator, and I've tried to investigate whether one could achieve a single-cell resolution for topological-domain detection.  I haven't been back to single-cell analysis in a while, so I haven't tried your package, but it looks very nice and promising.  FWIW, I've noticed that there are some movement toward "tidy" over at Bioconductor.

The reason why I ended up here this time was because I keep an eye out on reverse package dependencies for my **[future](cran.r-project.org/package=future)** package, of which **Seurat** is one, and then I looked one more generation down and spotted **tidyseurat**.

PS. Say hi to Tony from me.

**Comment by stemangiola** [comment]
Thanks, @HenrikBengtsson. I will say hi to Tony for you!

By the way, I tend to use `furrr` quite often and wanted to ask for a long time what is the whole business of `future` with Rstudio, and plans for the future.

I opened an issue on `future` repo as I think is more appropriate. Thanks for that library by the way.
