### ISSUE TITLE
Will you continue supporting future versions of Seurat?

### ISSUE THREAD

**Issue by chansigit** [stemangiola/tidyseurat#44]
In the bioinfo paper, tidyseurat is described as supporting seurat3. 
Seurat v4 has come to us for a while. Will you update tidyseurat when seurat v5, v6(if any) comes?

**Comment by chansigit** [comment]
I believe tidyverse style seurat is really helpful. come on, please keep updating.

**Comment by stemangiola** [comment]
This is the plan. Also with the help of the community. 

In what way you encounter tidyseurat to not be compatible with new versions of Seurat?

Could you please send us error messages?
