### ISSUE TITLE
Renaming genes

### ISSUE THREAD

**Issue by alwhiteh** [stemangiola/tidyseurat#53]
Hello,

I was wondering if tidyseurat is able to rename genes? I know that in base seurat, this is very difficult and often requires renaming the rows prior to constructing the seurat object and then rerunning all of the downstream processes. If possible, I would like to map orthologous genes to compare single cell data between species. 

Thanks!

-Alex

**Comment by stemangiola** [comment]
Hello @alwhiteh, tidyseurat deals with cell-related information, but unfortunately, no gene-related information. You will need to use standard Seurat/base R grammar to achieve that I believe.
