### ISSUE TITLE
Improve the documentation of tidytranscriptomics adapters, `tidySE`, `tidySCE`, `tidySPE`, `tidyseurat`

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidyseurat#66]
These issues Spence several packages. This includes:

All of these packages share 90% of the functions of the work done on one will be applicable to all the others.

- improving examples for methods
- solving documentation working (when packages are loading or installing)
- Improving methods' argument description

**Comment by stemangiola** [comment]
@william-hutchison do you want to add yourself to this challenge to port the updated annotation style of `tidySingleCellExperiment`?

from https://github.com/stemangiola/tidySingleCellExperiment/commit/dc27e23a7a4d3e13f6cd4e24c16dd2d6ba5a6700 for reference.

**Comment by GrootJ** [comment]
Happy to chip in as well!
Also thinking about where to start. I have a done bunch of NGS/omics analyses in R (incl using tidyverse grammar/structures). A bit newer to the summarized experiment containers/structures..
Also on slack channel, happy to discuss where I could help (with documentation, testing, etc?)

**Comment by stemangiola** [comment]
> Happy to chip in as well! Also thinking about where to start. I have a done bunch of NGS/omics analyses in R (incl using tidyverse grammar/structures). More of a user than a developer, and I am new to the summarized experiment containers/structures. Happy to discuss where I could help (with documentation, testing, etc?) - I am also on the slack channel..

Great. How about tackling `tidybulk` documentation? That is quite creative work and needs contributions at multiple levels

https://github.com/stemangiola/tidybulk/issues/282

But of course, if you want definitely to contribute to this one, we could discuss, and coordinate with @HelenaLC which is leading the `tidySingleCellExperiment` effort.

**Comment by stemangiola** [comment]
> Happy to chip in as well! Also thinking about where to start. I have a done bunch of NGS/omics analyses in R (incl using tidyverse grammar/structures). More of a user than a developer, and I am new to the summarized experiment containers/structures. Happy to discuss where I could help (with documentation, testing, etc?) - I am also on the slack channel..

Great. How about tackling `tidybulk` documentation? That is quite creative work and needs contributions at multiple levels

https://github.com/stemangiola/tidybulk/issues/282

But of course, if you want definitely to contribute to this one, we could discuss, and coordinate with @HelenaLC which is leading the `tidySingleCellExperiment` effort.

**Comment by stemangiola** [comment]
> Thanks @stemangiola; happy to chip in wherever I can! Haven't decided yet where to start; I'm on Slack as well, so happy to discuss.

Let us know if you are keen to start. Again `tidybulk` is a good option

https://github.com/stemangiola/tidybulk/issues/282

**Comment by GrootJ** [comment]
> > Happy to chip in as well! Also thinking about where to start. I have a done bunch of NGS/omics analyses in R (incl using tidyverse grammar/structures). More of a user than a developer, and I am new to the summarized experiment containers/structures. Happy to discuss where I could help (with documentation, testing, etc?) - I am also on the slack channel..
> 
> Great. How about tackling `tidybulk` documentation? That is quite creative work and needs contributions at multiple levels
> 
> [stemangiola/tidybulk#282](https://github.com/stemangiola/tidybulk/issues/282)
> 
> But of course, if you want definitely to contribute to this one, we could discuss, and coordinate with @HelenaLC which is leading the `tidySingleCellExperiment` effort.

I can contribute to `tidybulk` docs (have experience w bulk - can provide feedback there) - is it an issue listed a separately?
this is the repo https://github.com/stemangiola/tidybulk right? the current documentation is the github readme? 
Let me try to get the workflow going on my local machine.. probably good to touch base on goals etc

**Comment by stemangiola** [comment]
> > > Happy to chip in as well! Also thinking about where to start. I have a done bunch of NGS/omics analyses in R (incl using tidyverse grammar/structures). More of a user than a developer, and I am new to the summarized experiment containers/structures. Happy to discuss where I could help (with documentation, testing, etc?) - I am also on the slack channel..
> > 
> > 
> > Great. How about tackling `tidybulk` documentation? That is quite creative work and needs contributions at multiple levels
> > [stemangiola/tidybulk#282](https://github.com/stemangiola/tidybulk/issues/282)
> > But of course, if you want definitely to contribute to this one, we could discuss, and coordinate with @HelenaLC which is leading the `tidySingleCellExperiment` effort.
> 
> I can contribute to `tidybulk` docs - i have experience w bulk - can provide feedback there (no examples i can make public tho). you will also migrate the tidybulk issues to tidyomics repo right? the current documentation is the github readme? Let me try to get that workflow going on my local machine.. probably good to touch base on goals (zoom or other) some time

I have tagged you into the actual `tidybulk` issue.

**Comment by william-hutchison** [comment]
I will work on overhauling the tidySpatialExperiment documentation. Because tidySpatialExperiment is an extension of tidySingleCellExperiment, this will mainly involve copying across Helena's excellent changes.

**Comment by noriakis** [comment]
Hello, I would like to contribute to `tidyseurat` documentation. I would first try to do this with reference to @HelenaLC 's pull request for `tidySingleCellExperiment` https://github.com/stemangiola/tidySingleCellExperiment/pull/74.

**Comment by stemangiola** [comment]
> Hello, I would like to contribute to `tidyseurat` documentation. I would first try to do this with reference to @HelenaLC 's pull request for `tidySingleCellExperiment` [stemangiola/tidySingleCellExperiment#74](https://github.com/stemangiola/tidySingleCellExperiment/pull/74).

Amazing! @HelenaLC did quite a few PRs about this topic; I would suggest looking at the latest master branch of `tidySingleCellExperiment` directly. She simplified the documentation incredibly and made use of zzz.R.

**Comment by stemangiola** [comment]
Congrats to everyone involved! We refactored all packages mentioned in this issue!
