### ISSUE TITLE
Package suggested but not available: ‘BiocStyle’

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidyseurat#9]
Hello @mblue9 , I might need your experience one again.

Do you have idea why we do get this error for tisyseurat, but not for tidySCE?

```
 ❯ checking package dependencies ... ERROR
  Package suggested but not available: ‘BiocStyle’
```

**Comment by mblue9** [comment]
Having a look now. One difference is that tidyseurat uses the current release Bioc 3.11 whereas tidySCE uses Bioc3.12.
But there's probably no need for tidyseurat to use Biocstyle for the vignette as this isn't a Bioconductor package so could remove Biocstyle and just use regular html_vignette instead?

**Comment by mblue9** [comment]
So the underlying error seems to be knitr:
```
2020-10-19T12:37:01.0362536Z Bioconductor version 3.11 (BiocManager 1.30.10), ?BiocManager::install for help
2020-10-19T12:37:01.0364310Z ERROR: lazy loading failed for package ‘BiocStyle’
2020-10-19T12:37:01.0365189Z Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
2020-10-19T12:37:01.0366039Z   namespace ‘knitr’ 1.28 is being loaded, but >= 1.30 is required
2020-10-19T12:37:01.0366966Z Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
2020-10-19T12:37:01.0367583Z Execution halted
```
So could try adding knitr (>= 1.30) to DESCRIPTION? or is it best to just drop Biocstyle here if it's not really needed?

**Comment by stemangiola** [comment]
Isn't bioc style needed for the nice consistent layout of our webites? 

I'll try as you said.

**Comment by mblue9** [comment]
It's pkgdown that styles the websites, biocstyle is for the vignette available in CRAN and locally (I did a quick pkgdown build locally and doesn't make any noticeable difference to the website to me) but if you want have the tidyseurat vignette consistent with Bioc vignette then could keep biocstyle.

**Comment by stemangiola** [comment]
> if you want have the tidyseurat vignette consistent with Bioc vignette then could keep biocstyle

could not care less XD

**Comment by mblue9** [comment]
Ok I removed it here to see if it passes https://github.com/stemangiola/tidyseurat/pull/10
